name: "Poetry install"
description: "Installs the Poetry dependencies for a Python application"
inputs:
  python_version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install poetry
      shell: bash
      run: pip3 install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "${{ inputs.python_version }}"
        cache: poetry

    - name: Set Poetry environment
      shell: bash
      run: poetry env use ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: poetry install
