name: Repo sync

on:
  workflow_call:
    inputs:
      repository:
        description: 'Target repository (format git@github.com:owner/repo.git)'
        required: true
        type: string
      ref:
        description: 'Ref to sync'
        required: true
        type: string
        default: 'main'
      push_tags:
        description: 'If tags should be pushed to the target repository'
        required: false
        type: boolean
        default: false
    secrets:
      REPO_SYNC_PUSH_KEY:
        required: true

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" >> "$GITHUB_ENV"
          echo SSH_AGENT_PID="$SSH_AGENT_PID" >> "$GITHUB_ENV"

      - name: Add SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.REPO_SYNC_PUSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-add /home/runner/.ssh/github_actions

      - name: Sync repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --unset-all http.https://github.com/.extraheader
          git remote add public ${{ inputs.repository }}
          git push ${{ inputs.push_tags && '--tags' || '' }} public refs/remotes/origin/${{ inputs.ref }}
