name: 'Run SonarCloud scanner'
description: 'Runs the SonarCloud scanner.'
inputs:
  sonar-token:
    description: 'Sonar token'
    required: true
  project-base-dir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: 'Run SonarCloud scanner'
      if: ${{contains(github.ref, '/pull/')}}
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        projectBaseDir: ${{ inputs.project-base-dir }}
    - name: 'Run SonarCloud scanner'
      if: ${{!contains(github.ref, '/pull/')}}
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        projectBaseDir: ${{ inputs.project-base-dir }}
        args: -Dsonar.branch.name=${{ github.ref_name }}
