name: 'Run SonarCloud scanner'
description: 'Runs the SonarCloud scanner.'
inputs:
  sonar-token:
    description: 'Sonar token'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Run SonarCloud scanner'
      if: ${{contains(github.ref, '/pull/')}}
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
    - name: 'Run SonarCloud scanner'
      if: ${{!contains(github.ref, '/pull/')}}
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: -Dsonar.branch.name=${{ github.ref_name }}
